# Author: JHYeom
# Description: docker compose for kyhoon's code-server Dockerfile
version: '3.3'

services:
  code-server:
    build:
      dockerfile: Dockerfile
      context: .
      labels:
        - "com.example.description=code-server image kyhoon's customization"
    volumes:
      - $PWD:/home/coder/project
      - ~/.ssh:/home/coder/.ssh
    ports:
      - '127.0.0.1:${PORT}:8080'
      - '127.0.0.1:54321:54321'
