# Author: JHYeom
# Description: docker compose for kyhoon's code-server Dockerfile
version: '3.3'

services:
  code-server:
    container_name: code-server
    build:
      dockerfile: ./Dockerfile
      context: .
      labels:
        - "com.example.description=code-server image kyhoon's customization"
      args:
        - BASE_IMAGE=${BASE_IMAGE}
    image: code-server
    runtime: nvidia
    volumes:
      - ~/.ssh:/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD:/home/coder/project
      - /usr/local/cuda:/usr/local/cuda
    ports:
      - '127.0.0.1:${PORT}:8080'
      - '127.0.0.1:54321-54329:54321-54329'
